fn main() {
    linker_be_nice();

    slint_build::compile_with_config(
        "ui/app-window.slint",
        slint_build::CompilerConfiguration::new()
            .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer),
    )
    .expect("failed to compile the Slint UI");

    // linkall.x must remain the last linker script.
    println!("cargo:rustc-link-arg=-Tlinkall.x");
}

// Keep the linker diagnostics generated by esp-generate.
fn linker_be_nice() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 2 {
        let kind = &args[1];
        let what = &args[2];

        match kind.as_str() {
            "undefined-symbol" => match what.as_str() {
                what if what.starts_with("_defmt_") => {
                    eprintln!("`defmt` not found: add `defmt.x` and initialize a defmt transport");
                }
                "_stack_start" => {
                    eprintln!("the ESP linker script `linkall.x` is missing");
                }
                what if what.starts_with("esp_rtos_") => {
                    eprintln!("initialize `esp-rtos` or provide an external scheduler");
                }
                "embedded_test_linker_file_not_added_to_rustflags" => {
                    eprintln!("add the `embedded-test` linker script");
                }
                "free"
                | "malloc"
                | "calloc"
                | "get_free_internal_heap_size"
                | "malloc_internal"
                | "realloc_internal"
                | "calloc_internal"
                | "free_internal" => {
                    eprintln!("enable the required `esp-alloc` compatibility support");
                }
                _ => {}
            },
            _ => std::process::exit(1),
        }

        std::process::exit(0);
    }

    println!(
        "cargo:rustc-link-arg=-Wl,--error-handling-script={}",
        std::env::current_exe()
            .expect("build script path")
            .display()
    );
}
